- hosts: stephanlascar.me
  sudo: yes

  tasks:
    - name: install iptables-persistent
      action: apt name=iptables-persistent

    - name: copy the iptables file rules
      action: copy src=files/iptables_rules.v4 dest=/etc/iptables/rules.v4 owner=root group=root mode=0644
      notify: reload iptables-persistent

    - name: change firewall forward policy to ACCEPT
      command: sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
      notify: reload ufw

    - name: install docker.io
      action: apt name=docker.io

    - name: install nginx docker.io container
      command: docker pull nginx

    - name: create resume web directory
      file: path=/var/www state=directory

    - name: deploy resume web site
      action: copy src=files/resume dest=/var/www owner=root group=root mode=0644

    - name: check nginx docker.io container status
      shell: "docker ps -a | grep 'nginx' | cat"
      register: nginx_container_status

    - name: start nginx docker.io container
      command: docker run --name nginx -v /var/www/resume:/usr/share/nginx/html:ro -d -p 80:80 nginx
      when: (nginx_container_status.stdout.find('Up ') == -1)

  handlers:
    - name: reload iptables-persistent
      service: name=iptables-persistent state=reloaded

    - name: reload ufw
      command: ufw reload
