- name: install nginx docker.io container
  command: docker pull nginx

- name: create resume web directory
  file: path=/var/www state=directory

- name: deploy resume web site
  action: copy src=resume dest=/var/www owner=root group=root mode=0644

- name: check nginx docker.io container status
  shell: "docker ps -a | grep 'nginx' | cat"
  register: nginx_container_status

- name: start nginx docker.io container
  command: docker run --name nginx -v /var/www/resume:/usr/share/nginx/html:ro -d -p 8080:80 nginx
  when: (nginx_container_status.stdout.find('Up ') == -1)