- name: install ppa key
  apt_key: id=365C5CA1 url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x365C5CA1 state=present

- name: install ppa
  apt_repository: repo=ppa:transmissionbt/ppa state=present

- name: install Transmission
  apt: name=transmission-daemon state=present

- name: make sure transmission is not running
  service: name=transmission-daemon state=stopped
  ignore_errors: true

- name: copy Transmission configuration
  action: copy src=settings.json dest=/var/lib/transmission-daemon/info owner=root group=root mode=0644

- name: make sur transmission is started
  service: name=transmission-daemon state=started
  ignore_errors: true

- name: add apache vhosts configuration
  action: copy src=downloads.stephanlascar.me.conf dest=/etc/apache2/sites-available owner=root group=root mode=0644

- name: enable apache vhost website
  action: command a2ensite downloads.stephanlascar.me
  notify: reload apache
