- name: create a docker group
  group: name=docker state=present

- name: adding existing user 'stephan' to group docker
  user: name=stephan groups=docker append=yes

- name: install third-party packages
  apt: name={{item}} state=installed
  with_items:
       - apt-transport-https
       - ca-certificates

- name: remove deprecated docker package
  apt: name=lxc-docker state=absent

- name: remove deprecated docker apt repository
  apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=absent update_cache=no

- name: remove deprecated docker apt key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=absent

- name: install docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

- name: install docker apt repository
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main" state=present

- name: install third-party packages
  apt: name={{item}} state=installed
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual

- name: install docker
  apt: name=docker-engine state=installed

- name: fix DNS in docker
  lineinfile: dest=/etc/default/docker regexp="#DOCKER_OPTS=" line='DOCKER_OPTS="--dns 62.210.16.6 --dns 62.210.16.7"'
  notify: restart docker

- name: configure UFW’s forwarding policy
  lineinfile: dest=/etc/default/ufw regexp='DEFAULT_FORWARD_POLICY="DROP"' line='DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify: reload ufw
